Stocks: DecisionMethods Namespace Reference
DecisionMethods Namespace Reference
Functions
def randombuy (data, extraArg)
def weeklyrise (data, extraArg)
def dailyrise (data, extraArg)
def LS (data, extraArg)
def IRpred (data, Nx=1, Nf=5, ratio=0.03, days=5, extraArg)
Function Documentation
dailyrise()
def DecisionMethods.dailyrise (data, extraArg)
Definition at line 19 of file DecisionMethods.py.
Referenced by stocks.simulate().
 def dailyrise(data,**extraArg):
     difference=extraArg['difference']
     if(data[-1]>data[-2]*(1+difference)):
         return -1
     elif(data[-1]<data[-2]*(1-difference)):
         return 1
     else:
         return 0
IRpred()
def DecisionMethods.IRpred (data, Nx = 1, Nf = 5, ratio = 0.03, days = 5, extraArg)
Definition at line 48 of file DecisionMethods.py.
Referenced by stocks.simulate().
 def IRpred(data,Nx=1,Nf=5,ratio=0.03,days=5,**extraArg):
     #Args: Nx, Nf, ratio, days
     X=data[1:,0]
     F=data[:-1,1:]
     pred=IR(X,F,Nx,Nf)
     if(pred>(X[-days-1]*(1+ratio))):
         return -1
     elif(pred<(X[-days-1]*(1-ratio))):
         return 1
     else:
         return 0
LS()
def DecisionMethods.LS (data, extraArg)
Definition at line 28 of file DecisionMethods.py.
Referenced by stocks.simulate().
 def LS(data,**extraArg):
     difference=extraArg['difference']
     X=data[1:,0]
     F=data[:-1,1:]
     A=numpy.vstack([F.T,numpy.ones(len(X))]).T
     m=numpy.linalg.lstsq(A,X)[0]
     tomorrow=float(m[0]*F[-1]+m[1])
     logging.debug('X(end): {0:.2f}'.format(X[-1]))
     logging.debug('F(end): {0:.2f}'.format(float(data[-1,1:])))
     logging.debug('Tomorrow value: {0:.2f} from m: {1:.2f} c: {2:.2f}'.format(tomorrow,m[0],m[1]))
     if(tomorrow>X[-1]*(1+difference)):
         return -1
     elif(tomorrow<X[-1]*(1-difference)):
         return 1
     else:
         return 0
randombuy()
def DecisionMethods.randombuy (data, extraArg)
Definition at line 6 of file DecisionMethods.py.
Referenced by stocks.simulate().
 def randombuy(data,**extraArg):
     return randint(-1,1)
weeklyrise()
def DecisionMethods.weeklyrise (data, extraArg)
Definition at line 9 of file DecisionMethods.py.
 def weeklyrise(data,**extraArg):
     difference=extraArg['difference']
     if(data[-1]>data[-6]*(1+difference)):
         return -1
     elif(data[-1]<data[-6]*(1-difference)):
         return 1
     else:
         return 0